name: Docker Build (default)

on:
  workflow_dispatch:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  docker-default:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - uses: docker/setup-qemu-action@v1

    - uses: docker/setup-buildx-action@v1

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push image
      uses: docker/build-push-action@v2
      with:
        context: ./ubuntu/focal
        file: ./ubuntu/focal/Dockerfile
        push: true
        tags: ghcr.io/tyrubias/coursier-dev:latest
